<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>symbol1</name>
   <tag></tag>
   <elementGuidId>4c995aa6-0c9e-48cc-b690-a398c3c2842d</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>greek_symbol1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>symbol1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        None
                        Alpha
                        Beeta
                        Gama
                        Delta
                        Epsilon
                        Zeta
                        Eta
                        Theta
                        Iota
                        Kappa
                        Lambda
                        Mu
                        Nu
                        Xi
                        Omicron
                        Pi
                        Rho
                        Sigma
                        Tau
                        Upsilon
                        Phi
                        Chi
                        Psi
                        Omega
                    </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;greek_symbol1&quot;)</value>
   </webElementProperties>
</WebElementEntity>
