<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_albania</name>
   <tag></tag>
   <elementGuidId>df986d98-127b-4ada-ad62-ab69ce6d0c08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;mCSB_14_container&quot;)/div[@class=&quot;p-img1&quot;]/div[@class=&quot;crest-images&quot;]/img[@class=&quot;select_flag_img mCS_img_loaded&quot;][count(. | //img[@name = 'albania' and @class = 'select_flag_img mCS_img_loaded' and @src = 'http://newcollegewear.dev-fsit.com/wp-content/uploads/images/flags/IMG_flag_13062018122002.png']) = count(//img[@name = 'albania' and @class = 'select_flag_img mCS_img_loaded' and @src = 'http://newcollegewear.dev-fsit.com/wp-content/uploads/images/flags/IMG_flag_13062018122002.png'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>albania</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select_flag_img mCS_img_loaded</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://newcollegewear.dev-fsit.com/wp-content/uploads/images/flags/IMG_flag_13062018122002.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mCSB_14_container&quot;)/div[@class=&quot;p-img1&quot;]/div[@class=&quot;crest-images&quot;]/img[@class=&quot;select_flag_img mCS_img_loaded&quot;]</value>
   </webElementProperties>
</WebElementEntity>
